version: "3.8"

services:
  db:
    image: postgres:15
    container_name: wypozyczalnia-db
    environment:
      POSTGRES_DB: wypozyczalnia
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5433:5432"
    networks:
      - wypozyczalnia-network
    volumes:
      - wypozyczalnia-data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: wypozyczalnia-backend
    depends_on:
      db:
        condition: service_healthy
    networks:
      - wypozyczalnia-network
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/wypozyczalnia
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    container_name: wypozyczalnia-frontend
    networks:
      - wypozyczalnia-network
    ports:
      - "3000:80"

networks:
  wypozyczalnia-network:
    driver: bridge

volumes:
  wypozyczalnia-data:
